In [1]:
import pandas as pd
import numpy as np
pd.options.display.notebook_repr_html = False  # jupyter notebook上での出力形式を制御するために書いています。無くても動きます。

In [2]:
# 動作環境の確認
print(pd.__version__)
print(np.__version__)

1.1.2
1.19.1


pythonの普通のリストはappendがインプレースに行われる。

In [3]:
my_list = [1, 3, 5]
my_list

[1, 3, 5]

In [4]:
my_list.append(7)

In [5]:
my_list

[1, 3, 5, 7]

In [6]:
ret = my_list.append(9)
print(ret)

None


pandasではリストはappendがインプレースに行われない 返り値を取ってこなきゃいけない。

In [7]:
df = pd.DataFrame({'col_A': [1,2,3], 'col_B': ['p','q','r']})
df

   col_A col_B
0      1     p
1      2     q
2      3     r

In [8]:
df2 = pd.DataFrame({'col_A': [100, 200], 'col_B': ['x', 'y']})
df2

   col_A col_B
0    100     x
1    200     y

In [9]:
# 返り値は結合後のDataFrameとなる
df.append(df2)

   col_A col_B
0      1     p
1      2     q
2      3     r
0    100     x
1    200     y

In [10]:
# もとのDataFrameであるdfは変わっていない
df

   col_A col_B
0      1     p
1      2     q
2      3     r

appendにはinplace引数もない。  
ので、dfを新しくしようと思ったら、結果を代入する必要がある

In [11]:
df = df.append(df2)

In [12]:
df

   col_A col_B
0      1     p
1      2     q
2      3     r
0    100     x
1    200     y

In [13]:
# ループの中でappendする例
# 

df = pd.DataFrame()
for i in range(5):
    temp = {
        'num': i,
        'square': i**2,
        'cubic': i**3
    }
    df.append(temp, ignore_index=True)
    # appendの結果を代入していないので、dfはループの中で変わらない

In [14]:
# dfは空のDataFrameである
df

Empty DataFrame
Columns: []
Index: []

In [15]:
df = pd.DataFrame()
for i in range(5):
    temp = {
        'num': i,
        'square': i**2,
        'cubic': i**3
    }
    df = df.append(temp, ignore_index=True)


In [16]:
df

   cubic  num  square
0    0.0  0.0     0.0
1    1.0  1.0     1.0
2    8.0  2.0     4.0
3   27.0  3.0     9.0
4   64.0  4.0    16.0

In [17]:
df.dtypes

cubic     float64
num       float64
square    float64
dtype: object

おまけ：numpyってappendあったっけ?

In [18]:
numpy_array = np.array([1, 3, 5])
numpy_array

array([1, 3, 5])

In [19]:
# 返り値は結合後のNumPy配列となる
other = np.array([2, 4])
np.append(numpy_array, other)

array([1, 3, 5, 2, 4])

In [20]:
# もとのNumPy配列であるnumpy_arrayは変わっていない
numpy_array

array([1, 3, 5])