In [1]:
import numpy as np
import pandas as pd
pd.options.display.notebook_repr_html = False  # jupyter notebook上での出力形式を制御するために書いています。無くても動きます。

## numpy.arrayとnumpy.ndarrayの簡単な例

In [2]:
x = np.array([1, 2, 3])

In [3]:
x

array([1, 2, 3])

In [4]:
type(x)

numpy.ndarray

In [5]:
isinstance(x, np.ndarray)

True

## xを表示したときに登場するarrayとは何ものなのか?

> array([1, 2, 3])  

このarrayは何……???

https://numpy.org/doc/stable/glossary.html?highlight=array_like

numpyの「用語」だな。おそらく。

- pythonのlistから、numpy.array関数を使って、xを作りました。
- xはarray（numpy用語）です。
- xはnumpy.ndarrayクラスのインスタンスです。

## array-likeからarray（numpy用語）を作ろう
もしくはこういう言い方もできる
## array-likeからnumpy.ndarrayクラスのインスタンスを作ろう

array-likeには何が含まれているか

In [6]:
np.array(range(3, 7))

array([3, 4, 5, 6])

In [7]:
np.array((123, 456))

array([123, 456])

## pythonのリストやpandasのSeries/dataframeからNumPy配列にしたいんだけど?

In [8]:
x = np.array([[1, 2], [3, 4]])
x

array([[1, 2],
       [3, 4]])

In [9]:
df = pd.DataFrame({
    'col_A': [1 ,3, 5],
    'col_B': [9, 7, 5],
    'col_C': [111, 222, 333],
})
df

   col_A  col_B  col_C
0      1      9    111
1      3      7    222
2      5      5    333

In [10]:
x = np.array(df)
x

array([[  1,   9, 111],
       [  3,   7, 222],
       [  5,   5, 333]])

## だけど、ndarrayで配列（行列）を作ることも出来るよね?

In [11]:
np.ndarray((2, 3))

array([[111.,   0., 222.],
       [  0., 333.,   0.]])

In [12]:
np.ndarray((2, 4, 3))

array([[[-2.68156159e+154, -2.68156159e+154, -2.68156159e+154],
        [ 1.49457149e-154,  5.43472210e-323,  0.00000000e+000],
        [ 0.00000000e+000,  2.23989383e-314,  2.44328026e-314],
        [ 2.24882288e-314,  2.44229634e-314,  2.44015812e-314]],

       [[ 2.24049284e-314,  2.44181161e-314,  2.44180783e-314],
        [ 2.30309842e-314,  2.30097542e-314,  2.30323452e-314],
        [ 2.30309842e-314,  2.24055279e-314,  0.00000000e+000],
        [ 0.00000000e+000,  0.00000000e+000,  1.66880539e-308]]])

## arrayと書くべきところで、間違ってndarrayを使ってしまった例

In [13]:
# x = np.array([1, 2, 3]) が正しいのに
x = np.ndarray([1, 2, 3])

In [14]:
x

array([[[111.,   0., 222.],
        [  0., 333.,   0.]]])

In [15]:
# x = np.array(range(100)) が正しいのに
x = np.ndarray(range(100))

ValueError: maximum supported dimension for an ndarray is 32, found 100

In [16]:
# x = np.array([1.2, 3.4]) が正しいのに
x = np.ndarray([1.2, 3.4])

TypeError: 'float' object cannot be interpreted as an integer

In [17]:
# x = np.array(df) が正しいのに
x = np.ndarray(df)
x
# んー。よくわからないからブログには書かないでおこう

KeyError: 0

## ndarrayと書くべきところで、間違ってarrayを使ってしまった例

In [18]:
x = np.array([1, 2, 3])
# isinstance(x, np.ndarray) が正しいのに

isinstance(x, np.array)

TypeError: isinstance() arg 2 must be a type or tuple of types