In [1]:
import numpy as np
import pandas as pd

## arrayとndarrayの簡単な例

In [2]:
x = np.array([1, 2, 3])

In [3]:
x

array([1, 2, 3])

In [4]:
type(x)

numpy.ndarray

In [5]:
isinstance(x, (np.ndarray))

True

## 結果に登場するarray
> array([1, 2, 3])  

このarrayは何……???

https://numpy.org/doc/stable/glossary.html?highlight=array_like

numpyの「用語」だな。おそらく。

- pythonのlistから、numpy.array関数を使って、xを作りました。
- xはarray（numpy用語）です。
- xはnumpy.ndarrayクラスのインスタンスです。

## array-likeからarray（numpy用語）を作ろう
もしくはこういう言い方もできる
## array-likeからnumpy.ndarrayクラスのインスタンスを作ろう

array-likeには何が含まれているか

In [6]:
np.array(range(3, 7))

array([3, 4, 5, 6])

In [7]:
np.array((123, 456))

array([123, 456])

## numpyのarray（numpy用語）はpython標準のリストとは違うことを確認しようとした（けどうまく行かないや）

In [8]:
list_a = [1,2,3]
list_b = [1,2,3]
list_a == list_b

True

In [9]:
list_a == x

array([ True,  True,  True])