In [1]:
import numpy as np
import pandas as pd

## numpy.arrayとnumpy.ndarrayの簡単な例

In [2]:
x = np.array([1, 2, 3])

In [3]:
x

array([1, 2, 3])

In [4]:
type(x)

numpy.ndarray

In [5]:
isinstance(x, np.ndarray)

True

## xを表示したときに登場するarrayとは何ものなのか?

> array([1, 2, 3])  

このarrayは何……???

https://numpy.org/doc/stable/glossary.html?highlight=array_like

numpyの「用語」だな。おそらく。

- pythonのlistから、numpy.array関数を使って、xを作りました。
- xはarray（numpy用語）です。
- xはnumpy.ndarrayクラスのインスタンスです。

## array-likeからarray（numpy用語）を作ろう
もしくはこういう言い方もできる
## array-likeからnumpy.ndarrayクラスのインスタンスを作ろう

array-likeには何が含まれているか

In [6]:
np.array(range(3, 7))

array([3, 4, 5, 6])

In [7]:
np.array((123, 456))

array([123, 456])

## pythonのリストやpandasのSeries/dataframeからNumPy配列にしたいんだけど?

## だけど、ndarrayで配列（行列）を作ることも出来るよね?

In [8]:
np.ndarray((2, 3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [9]:
np.ndarray((2, 4, 3))

array([[[ 1.49166815e-154,  1.49166815e-154,  5.92878775e-323],
        [ 0.00000000e+000,  0.00000000e+000,  0.00000000e+000],
        [ 0.00000000e+000,  0.00000000e+000,  0.00000000e+000],
        [ 0.00000000e+000,  0.00000000e+000,  0.00000000e+000]],

       [[ 0.00000000e+000,  0.00000000e+000,  0.00000000e+000],
        [-1.73060078e-077,  1.49166815e-154, -2.00389880e+000],
        [ 1.97626258e-323,  0.00000000e+000,  0.00000000e+000],
        [ 0.00000000e+000,  1.49166815e-154,  1.67314295e-308]]])

## arrayと書くべきところで、間違ってndarrayを使ってしまった例

In [10]:
# x = np.array([1, 2, 3]) が正しいのに
x = np.ndarray([1, 2, 3])

In [11]:
x

array([[[0., 0., 0.],
        [0., 0., 0.]]])

In [12]:
# x = np.array(range(100)) が正しいのに
x = np.ndarray(range(100))

ValueError: maximum supported dimension for an ndarray is 32, found 100

In [13]:
# x = np.array([1.2, 3.4]) が正しいのに
x = np.ndarray([1.2, 3.4])

TypeError: 'float' object cannot be interpreted as an integer

## ndarrayと書くべきところで、間違ってarrayを使ってしまった例

In [14]:
x = np.array([1, 2, 3])
# isinstance(x, np.ndarray) が正しいのに

isinstance(x, np.array)

TypeError: isinstance() arg 2 must be a type or tuple of types